name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # - name: Check GITHUB_TOKEN
      #   run: echo "GITHUB_TOKEN is ${{ secrets.GITHUB_TOKEN }}"
      # - name: Print github.context
      #   run: |
      #     echo "github.context: ${{ toJson(github) }}"
      # - name: Print github.event
      #   run: |
      #     echo "github.event: ${{ toJson(github.event) }}"
      # - name: PRINT PR
      #   run: |
      #     echo "PR is ${{ toJson(github.event.pull_request) }}"
      # - name: Print PR title
      #   run: |
      #     echo "PR Title: ${{ github.event.pull_request.title }}"
      # - name: Print Base Ref
      #   run: |
      #     echo "Base Ref: ${{ github.event.pull_request.base.ref }}"
      # - name: Print Head Ref
      #   run: |
      #     echo "Head Ref: ${{ github.event.pull_request.head.ref }}"
      # - name: Print all environment variables
      #   run: env
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
