name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # - name: Check GITHUB_TOKEN
      #   run: echo "GITHUB_TOKEN is ${{ secrets.GITHUB_TOKEN }}"
      # - name: Print github.context
      #   run: |
      #     echo "github.context: ${{ toJson(github) }}"
      # - name: Print github.event
      #   run: |
      #     echo "github.event: ${{ toJson(github.event) }}"
      # - name: PRINT PR
      #   run: |
      #     echo "PR is ${{ toJson(github.event.pull_request) }}"
      # - name: Print PR title
      #   run: |
      #     echo "PR Title: ${{ github.event.pull_request.title }}"
      # - name: Print Base Ref
      #   run: |
      #     echo "Base Ref: ${{ github.event.pull_request.base.ref }}"
      # - name: Print Head Ref
      #   run: |
      #     echo "Head Ref: ${{ github.event.pull_request.head.ref }}"
      # - name: Print all environment variables
      #   run: env
      - id: lint_pr_title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
